[project]
name = "AutoSetSyntax"
version = "0.0.0"
description = "Automatically sets syntax based on various strategies."
readme = "README.md"
requires-python = ">=3.14.4,<3.15"
dependencies = [
  "more-itertools==11.*",
  "pydantic>=2,<3",
]

[project.urls]
Homepage = "https://github.com/jfcherng-sublime/ST-AutoSetSyntax"
Repository = "https://github.com/jfcherng-sublime/ST-AutoSetSyntax"
"Bug Tracker" = "https://github.com/jfcherng-sublime/ST-AutoSetSyntax/issues"
Changelog = "https://github.com/jfcherng-sublime/ST-AutoSetSyntax/blob/st4/CHANGELOG.md"

[dependency-groups]
dev = [
  "mypy>=2",
  "pytest>=9",
  "ruff>=0.15",
  "typing-extensions>=4.15",
  "vendorize<1",
]
docs = [
  "mkdocs-material==9.*",
  # mkdocs plugins
  "mkdocs-exclude==1.*",
  "mkdocs-git-revision-date-localized-plugin==1.*",
  "mkdocs-minify-plugin==0.8.*",
]

[tool.uv]
default-groups = ["dev"]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["."]

[tool.mypy]
# ignore_missing_imports = False
check_untyped_defs = true
strict_optional = true
mypy_path = 'typings:stubs'
python_version = '3.14'

[[tool.mypy.overrides]]
module = [
  "magika.*",
  "plugin._vendor.*",
]
ignore_errors = true
ignore_missing_imports = true

[tool.pyright]
include = ['./']
exclude = [
  '**/__pycache__/',
  '**/node_modules/',
  # git-related
  '**/.git/',
  '**/br-*/',
  '**/branch-*/',
]
ignore = ['**/.venv', '**/_vendor']
stubPath = 'typings'
pythonVersion = '3.14'

[tool.ruff]
preview = true
line-length = 120
target-version = 'py314'
exclude = [
  "*/libs/*",
  ".git",
  ".mypy_cache",
  ".venv",
  ".venv-*",
  "_vendor",
  "branch-*",
  "stubs",
  "tests/files",
  "typings",
  "venv",
  "venv-*",
]
extend-exclude = ["*.md"]

[tool.ruff.lint]
select = [
  "E",
  "F",
  "FURB",
  "I",
  "PERF",
  "SIM",
  "UP",
  "W",
]
ignore = ["E203"]

[tool.ruff.lint.isort]
force-single-line = true

[tool.ruff.lint.per-file-ignores]
"boot.py" = ["E402"]
