from _typeshed import Incomplete
from magika import colors as colors
from typing import TextIO

_logger: SimpleLogger | None

class SimpleLogger:
    """
    We implement a simple logger to not rely on additional python packages,
    e.g., rich. This is written in way that, by default, log messages (e.g.,
    debug/info/...) are sent to stderr.
    """
    level: Incomplete
    use_colors: Incomplete
    def __init__(self, use_colors: bool = False) -> None: ...
    def setLevel(self, level: int) -> None: ...
    def raw_print_to_stdout(self, msg: str) -> None: ...
    def raw_print(self, msg: str, file: TextIO | None = None, flush: bool = True) -> None: ...
    def debug(self, msg: str) -> None: ...
    def info(self, msg: str) -> None: ...
    def warning(self, msg: str) -> None: ...
    def error(self, msg: str) -> None: ...

def get_logger(use_colors: bool = False) -> SimpleLogger: ...
