from magika.logger import get_logger as get_logger
from magika.seekable import Buffer as Buffer, File as File, Seekable as Seekable
from magika.types import ContentTypeInfo as ContentTypeInfo, ContentTypeLabel as ContentTypeLabel, MagikaError as MagikaError, MagikaPrediction as MagikaPrediction, MagikaResult as MagikaResult, ModelConfig as ModelConfig, ModelFeatures as ModelFeatures, ModelOutput as ModelOutput, PredictionMode as PredictionMode, Status as Status
from pathlib import Path

DEFAULT_MODEL_NAME: str

class Magika:
    def __init__(self, model_dir: Path | None = None, prediction_mode: PredictionMode = ..., no_dereference: bool = False, verbose: bool = False, debug: bool = False, use_colors: bool = False) -> None: ...
    def identify_path(self, path: Path) -> MagikaResult: ...
    def identify_paths(self, paths: list[Path]) -> list[MagikaResult]: ...
    def identify_bytes(self, content: bytes) -> MagikaResult: ...
    def get_supported_content_types(self) -> list[ContentTypeLabel]: ...
    def get_model_dir_name(self) -> str: ...
