import abc
from pathlib import Path

class Seekable(abc.ABC, metaclass=abc.ABCMeta):
    def __init__(self) -> None: ...
    @property
    def size(self) -> int: ...
    @abc.abstractmethod
    def read_at(self, offset: int, size: int) -> bytes: ...
    def close(self) -> None: ...

class File(Seekable):
    def __init__(self, path: Path) -> None: ...
    def read_at(self, offset: int, size: int) -> bytes: ...
    def close(self) -> None: ...

class Buffer(Seekable):
    def __init__(self, buffer: bytes) -> None: ...
    def read_at(self, offset: int, size: int) -> bytes: ...
