name: Docs

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    paths:
      - '.github/workflows/docs.yml'
      - 'docs/**'
      - 'Makefile'
      # referenced external files
      - 'CHANGELOG.md'

jobs:
  job_build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v8.2.0
      - run: |
          make install-docs
          make docs-build
  job_deploy:
    # deploy only on the "stable" branch
    if: ${{ github.ref == 'refs/heads/stable' }}
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v8.2.0
      - run: |
          make install-docs
          make docs-deploy
