name: Docs
on:
  push:
    paths:
      - '.github/workflows/docs.yml'
      - 'docs/**'
      - 'Makefile'
      # referenced external files
      - 'CHANGELOG.md'

jobs:
  job_build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: astral-sh/setup-uv@v6
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      - run: |
          make docs-build
  job_deploy:
    # deploy only on the "stable" branch
    if: ${{ github.ref == 'refs/heads/stable' }}
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: astral-sh/setup-uv@v6
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      - run: |
          make docs-deploy
