# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - '**'
    paths:
      - '.github/workflows/python.yml'
      - '**.py'
      - '**.pyi'
      - 'Makefile'
      - 'pyproject.toml'
      - 'uv.lock'
      - 'tests/**'
  pull_request:
    branches:
      - '**'
    paths:
      - '.github/workflows/python.yml'
      - '**.py'
      - '**.pyi'
      - 'Makefile'
      - 'pyproject.toml'
      - 'uv.lock'
      - 'tests/**'

jobs:
  job_lint:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v8.2.0
      - name: Do unit test
        run: make ci-test
      - name: Do linting
        run: make ci-check
